### ISSUE TITLE
Outgroup selection

### ISSUE THREAD

**Issue by XMTian** [ksiewert/BetaScan#19]
Hi,

Thanks for designing this awesome software.

I have some questions regarding how to choose the outgroup. 
1. What is the principle of outgroup selection and what is the maximum divergence time?
2. Should I take the mapping ratio (when I map the outgroup to my species) into account when I choose the outgroup?
3. If my species has a sister species, the assumption should be the balancing selection is only acting on my species, not the sister species, is it correct?

Best,
Xiaomeng

**Comment by ksiewert** [comment]
Hi Xiaomeng, Great questions!

1) Generally, the best choice of outgroup is the species that is close enough to your species of interest that there is high homology between them, but that is diverged enough that there will be a non-trivial number of substitutions that would occur under neutrality.

2) I recommend only applying the B2 statistics on regions where there is high confidence in the mapping from one species to another. I'm not too familiar with mapping ratios, so I'll leave it to you to figure out what you think the cutoff should be.

3) Applying Betascan to regions of shared selection should be fine since BetaScan uses substitutions as a signal that there is a decrease in fixation at a locus compared to neutrality. However, if your species has a sister species and you think there could be shared balancing selection, I think looking for trans-species haplotypes is a better approach that is less prone to false positives. Some great references for this are Leffler et al 2013 Science and Gao et al 2015 Evolution. 

Hope this helps!
