### ISSUE TITLE
Using only exonic biallelic sites for beta1 analysis

### ISSUE THREAD

**Issue by Dipti-IISERpune** [ksiewert/BetaScan#22]
Hi, I am using betascan to measure the beta1 in biallelic sites. but Highest values are present in the intronic or UTR or intergenic region. Would you advise to use beta1 for exonic region?  Thank you.

**Comment by ksiewert** [comment]
Hello! It's great that you caught that you're seeing the highest values in non-exonic regions. This is likely caused by the higher mutation rate in these regions due to weaker negative selection. Are you using the original (unstandardized) version of beta1? If so, I would switch to using the standardized version. This should correct for the background level of mutation rate in the window.

**Comment by Dipti-IISERpune** [comment]
Thank you for quick response. I could not find the standardised version. Will you please help me out which version would best fit my data. I don't have an outgroup to specify. Just 6 individual samples belonging to different generations.

**Comment by ksiewert** [comment]
Check out the --std flag in this section of the readme: https://github.com/ksiewert/BetaScan/wiki/Basic-Usage#parameters. For the scientific details you can read our [BetaScan2 paper](https://academic.oup.com/gbe/article/12/2/3873/5721358).
