### ISSUE TITLE
compare two populations

### ISSUE THREAD

**Issue by DongmeiDai** [ksiewert/BetaScan#25]
Hello,
If I want to compare the level of balanced selection between two populations, can I use a mean comparison of beta 1 or beta 2?

Thanks

**Comment by xixifa** [comment]
Hello,
I have four populations that were initially controlled based on deletion rates and minimum allele frequencies, so each population had a different number of remaining SNPS. May I ask whether the epo file can be set according to the number of SNPS in different groups？ This means I have four epo files based on the SNP number, is it right?

Thank you very much

**Comment by ksiewert** [comment]
I know you asked this a long time ago, but I'm just seeing this now. Any population that tends to have longer TMRCAs will tend to have higher Beta scores, whether the long TMRCAs are because of balancing selection or because of various demographic forces. For this reason, I don't recommend comparing Beta scores across populations.
