### ISSUE TITLE
Negative value

### ISSUE THREAD

**Issue by SC-Duan** [ksiewert/BetaScan#3]
Hi,
Thank you for the friendly script!
I found a large proportion of negative values were in the output of Beta1*, is this normal?
Thank you!

**Comment by ksiewert** [comment]
Hello,

Negative values are expected and normal. What proportion of your values are negative? As long as it's not more than about 50%, it sounds like Beta is behaving normally. I do strongly recommend using the -m flag with Beta1*, as Beta1* can be prone to noisy behavior at the extreme end of the site frequency spectrum. If you're getting a huge number of negative values at very low frequency SNPs, this could be your issue.

If you want to see the distribution of Beta values we got when applying to humans, check out supplementary figure 3 in our MBE paper. You'll see that there's a significant proportion of SNPs with scores below zero in all populations. This plot is for Beta1, not Beta1*, but the Beta1* distribution looks very similar.

Negative values occur because the expected value of Beta1* is zero, so if you were to calculate Beta1* using a random core frequency on a random window, there's close to a 50% chance that the value would be negative. This occurs when by chance Watterson's theta is larger theta_beta.

**Comment by ksiewert** [comment]
Another thing to keep in mind, using the -m flag is important when using Beta1*.
